### ISSUE TITLE
BANK File format?

### ISSUE THREAD

**Issue by Bleech-Studios** [bgbennyboy/Telltale-Music-Extractor#3]
just wondering (this is not an issue)
What is the format for BANK files?
Im converting lots of telltale extraction programs into java (you would get credit) and the bank files are a weird one
I tried looking at the pascal source, but you are using APIs that you have made which arent on the github here.
Thanks

**Comment by bgbennyboy** [comment]
I dont know the format and as far as I know no-one else does. The approach I took was to build a separate tool (FSB Bank Dumper) that uses the fmod API to dump them.

**Comment by Bleech-Studios** [comment]
Aah okay,
But do you know if the files are encrypted? And if they are, which encryption, and what keys?

**Comment by bgbennyboy** [comment]
I cant remember, I think they were inside the ttatch bundles, which are
encrypted

**Comment by bgbennyboy** [comment]
What exactly is it you are trying to make?

**Comment by Bleech-Studios** [comment]
However, I did see this
https://zenhax.com/viewtopic.php?t=3462
Not sure if it applies though

**Comment by Bleech-Studios** [comment]
Luigi auriemma made a fsb extractor which works though,
Im going to look at the C code and maybe convert it into java then. Apparently it does not use encryption

**Comment by bgbennyboy** [comment]
.bank files are a newer type of FSB that arent supported in aluigi's fsb extractor as far as I know.
If you want to extract from .bank files use my FSB Bank Dumper tool from this repository or this tool which uses the same approach https://zenhax.com/viewtopic.php?f=17&t=1901

**Comment by Bleech-Studios** [comment]
Is there a source for that?

**Comment by bgbennyboy** [comment]
The source for mine is in this repository, the other one I have no idea

**Comment by Bleech-Studios** [comment]
Got it, thanks for that. Ill use the JNI (java native interface for using C &cpp code with java) to use the dlls needed for fmod and I can use then in the extractor. Ill have a look at your code too to see how this works
